### ISSUE TITLE
Unable to do npm install

### ISSUE THREAD

**Issue by kannangce** [mcguinness/saml-sp#11]
Getting the below error when trying to do `npm install`,
```
/usr/local/bin/saml-sp -> /usr/local/lib/node_modules/saml-sp/bin/server.js

> x509@0.3.3 install /Users/<user_name>/Desktop/Kannan/projects/saml-sp/node_modules/x509
> node-gyp rebuild

  CXX(target) Release/obj.target/x509/src/addon.o
In file included from ../src/addon.cc:5:
In file included from ../include/x509.h:7:
In file included from ../../nan/nan.h:194:
../../nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
../../nan/nan_maybe_43_inl.h:220:17: error: no member named 'CloneElementAt' in 'v8::Array'
  return array->CloneElementAt(GetCurrentContext(), index);
         ~~~~~  ^
In file included from ../src/addon.cc:5:
In file included from ../include/x509.h:7:
In file included from ../../nan/nan.h:200:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:40:38: error: too few arguments to function call, expected 2, have 1
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
         ~~~~~~~~~~~~~~~~~~~~~~      ^
/Users/<user_name>/.node-gyp/11.14.0/include/node/v8.h:5224:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, bool value);
  ^
In file included from ../src/addon.cc:5:
In file included from ../include/x509.h:7:
In file included from ../../nan/nan.h:200:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:40:60: error: expected '(' for function-style cast or type construction
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                          ~~~~~~~~~~~~~~~~~^
../../nan/nan_implementation_12_inl.h:40:62: error: expected expression
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                                             ^
../../nan/nan_implementation_12_inl.h:340:28: warning: 'New' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
/Users/<user_name>/.node-gyp/11.14.0/include/node/v8.h:5241:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/<user_name>/.node-gyp/11.14.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/addon.cc:5:
In file included from ../include/x509.h:7:
../../nan/nan.h:820:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/<user_name>/.node-gyp/11.14.0/include/node/node.h:173:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/<user_name>/.node-gyp/11.14.0/include/node/node.h:93:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/addon.cc:5:
In file included from ../include/x509.h:7:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/<user_name>/.node-gyp/11.14.0/include/node/node.h:166:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/<user_name>/.node-gyp/11.14.0/include/node/node.h:93:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/addon.cc:5:
In file included from ../include/x509.h:7:
../../nan/nan.h:848:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/<user_name>/.node-gyp/11.14.0/include/node/node.h:159:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/<user_name>/.node-gyp/11.14.0/include/node/node.h:93:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/addon.cc:5:
In file included from ../include/x509.h:7:
../../nan/nan.h:894:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();
                                           ^
/Users/<user_name>/.node-gyp/11.14.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/<user_name>/.node-gyp/11.14.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/addon.cc:5:
In file included from ../include/x509.h:7:
../../nan/nan.h:904:27: warning: 'WriteUtf8' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                          ^
/Users/<user_name>/.node-gyp/11.14.0/include/node/v8.h:2753:3: note: 'WriteUtf8' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/<user_name>/.node-gyp/11.14.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/addon.cc:5:
In file included from ../include/x509.h:7:
../../nan/nan.h:1461:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/<user_name>/.node-gyp/11.14.0/include/node/node.h:173:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/<user_name>/.node-gyp/11.14.0/include/node/node.h:93:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/addon.cc:5:
In file included from ../include/x509.h:7:
../../nan/nan.h:1965:7: error: no viable conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'Local<v8::Name>'
    , getter_
      ^~~~~~~
/Users/<user_name>/.node-gyp/11.14.0/include/node/v8.h:303:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'imp::NativeGetter' (aka
      'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'const v8::Local<v8::Name> &' for 1st argument
class Local {
      ^
/Users/<user_name>/.node-gyp/11.14.0/include/node/v8.h:303:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'imp::NativeGetter' (aka
      'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'v8::Local<v8::Name> &&' for 1st argument
/Users/<user_name>/.node-gyp/11.14.0/include/node/v8.h:307:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'void (*)(v8::Local<v8::Name>,
      const v8::PropertyCallbackInfo<v8::Value> &)'
  V8_INLINE Local(Local<S> that)
            ^
/Users/<user_name>/.node-gyp/11.14.0/include/node/v8.h:3455:43: note: passing argument to parameter 'name' here
      Local<Context> context, Local<Name> name,
                                          ^
/Users/<user_name>/.node-gyp/11.14.0/include/node/v8.h:314:5: error: assigning to 'v8::Context *' from incompatible type 'v8::String *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/<user_name>/.node-gyp/11.14.0/include/node/v8.h:268:39: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                      ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:1964:7: note: in instantiation of function template specialization 'v8::Local<v8::Context>::Local<v8::String>' requested here
      name
      ^
7 warnings and 7 errors generated.
make: *** [Release/obj.target/x509/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/11.14.0_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/<user_name>/Desktop/Kannan/projects/saml-sp/node_modules/x509
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN rollback Rolling back nan@2.2.0 failed (this is probably harmless): /Users/<user_name>/Desktop/Kannan/projects/saml-sp/node_modules/nan is not a child of /usr/local/lib
npm WARN rollback Rolling back x509@0.3.3 failed (this is probably harmless): /Users/<user_name>/Desktop/Kannan/projects/saml-sp/node_modules/x509 is not a child of /usr/local/lib
npm WARN rollback Rolling back passport-wsfed-saml2@3.0.17 failed (this is probably harmless): /Users/<user_name>/Desktop/Kannan/projects/saml-sp/node_modules/passport-wsfed-saml2 is not a child of /usr/local/lib
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! x509@0.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the x509@0.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by raghu-icecraft-fullstack** [comment]
@kannangce, @mcguinness : 
I just did npm install today of saml-sp repo. And `npm install` worked fine.

My environment is Ubuntu 18.04 thru WSL2 on Windows 10.
I did not see issues in npm install.

Just wanted to provide an update. And may be might be issued.

These are my node and npm versions, just in case.
```
$ node -v
v8.10.0
$ npm -v
3.5.2
```

**Comment by mdorn** [comment]
I have the same problems as @kannangce - rolling back to an earlier commit `4ccba9203988125cbf92cd6e398f325bec72c43c` at least made it install properly

**Comment by mcguinness** [comment]
reverted passport-wsfed-saml2 dependency that has a known issue with `x509` lib on osx.  Should work now

**Comment by mdorn** [comment]
That did the trick thanks @mcguinness
